FROM maven:ibmjava-alpine AS builder

WORKDIR /app
COPY . .
RUN mvn clean package 
RUN ls -alh /app/target

CMD ["java", "-Djava.security.edg=file:/dev/./urandom", "-jar", "/app/target/websocket-demo-0.0.1-SNAPSHOT.jar"]


